import os
from datetime import datetime, timedelta
from typing import List, Optional, Any

from fastapi import FastAPI, Depends, HTTPException, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.security import OAuth2PasswordBearer, OAuth2PasswordRequestForm
from fastapi.openapi.docs import get_swagger_ui_html, get_redoc_html
from pydantic import BaseModel, EmailStr, Field
from jose import JWTError, jwt
from passlib.context import CryptContext
from dotenv import load_dotenv
import httpx

# Load environment variables (OPENAI_API_KEY expected)
load_dotenv()

# =============================================================================
# Configuration and constants
# =============================================================================

SECRET_KEY = os.getenv("JWT_SECRET_KEY", "change-this-in-env")
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = int(os.getenv("JWT_EXPIRE_MINUTES", "60"))
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

# In-memory "database" (for demo). In a real app, replace with a proper DB.
DB = {
    "users": [],       # list of dicts
    "questions": [],   # list of dicts
    "answers": [],     # list of dicts
}

# Security setup
pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/auth/login")

# =============================================================================
# Pydantic models
# =============================================================================

class Token(BaseModel):
    access_token: str = Field(..., description="JWT access token")
    token_type: str = Field(..., description="Type of token; typically 'bearer'")

class TokenData(BaseModel):
    user_id: Optional[int] = Field(None, description="User ID from token subject")

class UserBase(BaseModel):
    email: EmailStr = Field(..., description="User email")
    full_name: Optional[str] = Field(None, description="Full name")

class UserCreate(UserBase):
    password: str = Field(..., min_length=6, description="User password")

class UserOut(UserBase):
    id: int = Field(..., description="User identifier")

class QuestionBase(BaseModel):
    title: str = Field(..., min_length=3, max_length=200, description="Question title")
    body: str = Field(..., min_length=3, description="Question details")

class QuestionCreate(QuestionBase):
    pass

class QuestionOut(QuestionBase):
    id: int = Field(..., description="Question identifier")
    user_id: int = Field(..., description="Author user ID")
    created_at: datetime = Field(..., description="Creation timestamp")

class AnswerBase(BaseModel):
    body: str = Field(..., min_length=1, description="Answer text")

class AnswerCreate(AnswerBase):
    question_id: int = Field(..., description="Related question ID")

class AnswerOut(AnswerBase):
    id: int = Field(..., description="Answer identifier")
    question_id: int = Field(..., description="Related question ID")
    user_id: Optional[int] = Field(None, description="Author user ID (None if AI generated)")
    created_at: datetime = Field(..., description="Creation timestamp")
    is_ai_generated: bool = Field(False, description="Flag indicating if answer was generated by AI")

# =============================================================================
# Utility functions
# =============================================================================

def verify_password(plain_password: str, hashed_password: str) -> bool:
    return pwd_context.verify(plain_password, hashed_password)

def get_password_hash(password: str) -> str:
    return pwd_context.hash(password)

def create_access_token(data: dict, expires_delta: Optional[timedelta] = None) -> str:
    to_encode = data.copy()
    expire = datetime.utcnow() + (expires_delta or timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES))
    to_encode.update({"exp": expire})
    encoded_jwt = jwt.encode(to_encode, SECRET_KEY, algorithm=ALGORITHM)
    return encoded_jwt

def get_user_by_email(email: str) -> Optional[dict]:
    return next((u for u in DB["users"] if u["email"].lower() == email.lower()), None)

def get_user_by_id(user_id: int) -> Optional[dict]:
    return next((u for u in DB["users"] if u["id"] == user_id), None)

async def get_current_user(token: str = Depends(oauth2_scheme)) -> dict:
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials.",
        headers={"WWW-Authenticate": "Bearer"},
    )
    try:
        payload = jwt.decode(token, SECRET_KEY, algorithms=[ALGORITHM])
        sub: Optional[int] = payload.get("sub")
        if sub is None:
            raise credentials_exception
        token_data = TokenData(user_id=int(sub))
    except JWTError:
        raise credentials_exception
    user = get_user_by_id(token_data.user_id) if token_data.user_id is not None else None
    if user is None:
        raise credentials_exception
    return user

def next_id(key: str) -> int:
    if not DB[key]:
        return 1
    return max(item["id"] for item in DB[key]) + 1

# =============================================================================
# OpenAI integration
# =============================================================================

async def call_openai_chat(prompt: str) -> str:
    """
    Calls OpenAI Chat Completions API to generate an answer.
    Uses OPENAI_API_KEY environment variable.
    """
    if not OPENAI_API_KEY:
        # Provide a helpful error to operator; API still responds gracefully.
        raise HTTPException(
            status_code=500,
            detail="OPENAI_API_KEY is not set. Please configure it in the environment."
        )

    # Using the new Responses API would be possible, but we'll use chat completions for compatibility.
    url = "https://api.openai.com/v1/chat/completions"
    headers = {
        "Authorization": f"Bearer {OPENAI_API_KEY}",
        "Content-Type": "application/json",
    }
    payload = {
        "model": "gpt-4o-mini",
        "messages": [
            {"role": "system", "content": "You are a helpful assistant for a Q&A application."},
            {"role": "user", "content": prompt},
        ],
        "temperature": 0.2,
    }

    async with httpx.AsyncClient(timeout=60.0) as client:
        resp = await client.post(url, headers=headers, json=payload)
        if resp.status_code >= 400:
            raise HTTPException(status_code=resp.status_code, detail=f"OpenAI error: {resp.text}")
        data = resp.json()
        content = data["choices"][0]["message"]["content"]
        return content.strip()

# =============================================================================
# FastAPI app
# =============================================================================

app = FastAPI(
    title="QnA Backend API",
    description=(
        "Handles user authentication, questions, and answers. "
        "Integrates with OpenAI to generate answers. "
        "Theme: Ocean Professional (blue & amber accents)."
    ),
    version="1.0.0",
    contact={
        "name": "QnA Platform",
        "url": "https://example.com",
    },
    license_info={
        "name": "MIT",
        "url": "https://opensource.org/licenses/MIT",
    },
    openapi_tags=[
        {"name": "Health", "description": "Health checks and service info"},
        {"name": "Auth", "description": "User authentication (signup, login, profile)"},
        {"name": "Questions", "description": "Create and list questions"},
        {"name": "Answers", "description": "Generate and list answers"},
    ],
)

# CORS for Angular frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],  # In production, restrict to actual frontend URL.
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# =============================================================================
# Themed Docs (Ocean Professional)
# =============================================================================

OCEAN_PRIMARY = "#2563EB"
OCEAN_AMBER = "#F59E0B"
OCEAN_ERROR = "#EF4444"
OCEAN_TEXT = "#111827"
OCEAN_BG = "#f9fafb"
OCEAN_SURFACE = "#ffffff"

SWAGGER_CUSTOM_CSS = f"""
:root {{
  --primary: {OCEAN_PRIMARY};
  --secondary: {OCEAN_AMBER};
  --text: {OCEAN_TEXT};
  --surface: {OCEAN_SURFACE};
  --bg: {OCEAN_BG};
}}

html, body {{
  background: var(--bg) !important;
  color: var(--text) !important;
}}

.topbar, .swagger-ui .info {{
  background: linear-gradient(135deg, rgba(37,99,235,0.10), rgba(243,244,246,1));
  border-bottom: 1px solid #e5e7eb;
}}

.swagger-ui .topbar .download-url-wrapper .select-label {{
  color: var(--text);
}}

.swagger-ui .topbar .download-url-wrapper input[disabled] {{
  background-color: #eef2ff;
}}

.swagger-ui .btn.authorize, .opblock-summary-control {{
  border-radius: 10px !important;
}}

.swagger-ui .btn.authorize {{
  background-color: {OCEAN_PRIMARY} !important;
  border-color: {OCEAN_PRIMARY} !important;
}}

.swagger-ui .btn.execute.opblock-control__btn {{
  background-color: {OCEAN_AMBER} !important;
  border-color: {OCEAN_AMBER} !important;
  color: #1f2937 !important;
}}

.opblock-summary-method, .opblock-summary-path, .opblock-summary-operation-id {{
  border-radius: 6px;
}}

.swagger-ui .opblock {{
  border-radius: 12px;
  box-shadow: 0 2px 10px rgba(17,24,39,0.05);
}}

.swagger-ui .errors-wrapper {{
  color: {OCEAN_ERROR} !important;
}}
"""

@app.get("/docs", include_in_schema=False)
def custom_swagger_ui_html() -> Any:
    """
    PUBLIC_INTERFACE
    Returns the Swagger UI with Ocean Professional theme overrides.
    """
    return get_swagger_ui_html(
        openapi_url=app.openapi_url,
        title=app.title + " - Docs",
        swagger_favicon_url="",
        oauth2_redirect_url=app.swagger_ui_oauth2_redirect_url,
        swagger_js_url="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui-bundle.js",
        swagger_css_url="https://cdn.jsdelivr.net/npm/swagger-ui-dist@5/swagger-ui.css",
        init_oauth=None,
        swagger_ui_parameters={"docExpansion": "list", "defaultModelsExpandDepth": 1},
        **{"custom_css": SWAGGER_CUSTOM_CSS},
    )

@app.get("/redoc", include_in_schema=False)
def redoc_html() -> Any:
    """
    PUBLIC_INTERFACE
    Returns ReDoc UI.
    """
    return get_redoc_html(
        openapi_url=app.openapi_url,
        title=app.title + " - ReDoc",
    )

# =============================================================================
# Health
# =============================================================================

@app.get("/", tags=["Health"], summary="Health Check", description="Check if the service is running.")
def health_check():
    """
    PUBLIC_INTERFACE
    Returns a simple health check response with server time.
    """
    return {"status": "ok", "time": datetime.utcnow().isoformat()}

# =============================================================================
# Auth routes
# =============================================================================

@app.post("/auth/signup", response_model=UserOut, tags=["Auth"], summary="User signup", description="Create a new user account.")
def signup(user_in: UserCreate):
    """
    PUBLIC_INTERFACE
    Signup endpoint. Creates a new user with hashed password.

    Parameters:
    - user_in: UserCreate - email, full_name, password

    Returns:
    - UserOut: id, email, full_name
    """
    if get_user_by_email(user_in.email) is not None:
        raise HTTPException(status_code=400, detail="Email already registered.")
    uid = next_id("users")
    user = {
        "id": uid,
        "email": user_in.email,
        "full_name": user_in.full_name,
        "hashed_password": get_password_hash(user_in.password),
        "created_at": datetime.utcnow(),
    }
    DB["users"].append(user)
    return {"id": user["id"], "email": user["email"], "full_name": user["full_name"]}

@app.post("/auth/login", response_model=Token, tags=["Auth"], summary="User login", description="Authenticate user and obtain JWT access token.")
def login(form_data: OAuth2PasswordRequestForm = Depends()):
    """
    PUBLIC_INTERFACE
    Login endpoint.

    Accepts:
    - OAuth2PasswordRequestForm (username=email, password)

    Returns:
    - Token: access_token, token_type
    """
    user = get_user_by_email(form_data.username)
    if not user or not verify_password(form_data.password, user["hashed_password"]):
        raise HTTPException(status_code=400, detail="Incorrect email or password.")
    access_token_expires = timedelta(minutes=ACCESS_TOKEN_EXPIRE_MINUTES)
    token = create_access_token(data={"sub": str(user["id"])}, expires_delta=access_token_expires)
    return {"access_token": token, "token_type": "bearer"}

@app.get("/auth/me", response_model=UserOut, tags=["Auth"], summary="Get current user", description="Retrieve the authenticated user's profile.")
def read_users_me(current_user: dict = Depends(get_current_user)):
    """
    PUBLIC_INTERFACE
    Returns the current authenticated user's profile.
    """
    return {"id": current_user["id"], "email": current_user["email"], "full_name": current_user.get("full_name")}

# =============================================================================
# Question routes
# =============================================================================

@app.post(
    "/questions",
    response_model=QuestionOut,
    tags=["Questions"],
    summary="Create question",
    description="Create a new question. Requires authentication.",
    responses={
        401: {"description": "Unauthorized"},
        422: {"description": "Validation error"},
    },
)
async def create_question(question_in: QuestionCreate, current_user: dict = Depends(get_current_user)):
    """
    PUBLIC_INTERFACE
    Creates a question associated with the authenticated user.

    Parameters:
    - question_in: QuestionCreate - title, body

    Returns:
    - QuestionOut
    """
    qid = next_id("questions")
    now = datetime.utcnow()
    q = {
        "id": qid,
        "title": question_in.title,
        "body": question_in.body,
        "user_id": current_user["id"],
        "created_at": now,
    }
    DB["questions"].append(q)
    return QuestionOut(**q)

@app.get(
    "/questions",
    response_model=List[QuestionOut],
    tags=["Questions"],
    summary="List questions",
    description="Retrieve list of all questions ordered by newest first."
)
async def list_questions():
    """
    PUBLIC_INTERFACE
    Returns a list of all questions.
    """
    items = sorted(DB["questions"], key=lambda x: x["created_at"], reverse=True)
    return [QuestionOut(**q) for q in items]

@app.get(
    "/questions/{question_id}",
    response_model=QuestionOut,
    tags=["Questions"],
    summary="Get question by ID",
    description="Retrieve a single question by its ID."
)
async def get_question(question_id: int):
    """
    PUBLIC_INTERFACE
    Get a question by ID.
    """
    q = next((x for x in DB["questions"] if x["id"] == question_id), None)
    if not q:
        raise HTTPException(status_code=404, detail="Question not found.")
    return QuestionOut(**q)

# =============================================================================
# Answer routes
# =============================================================================

@app.get(
    "/answers",
    response_model=List[AnswerOut],
    tags=["Answers"],
    summary="List answers",
    description="List all answers, newest first."
)
async def list_answers():
    """
    PUBLIC_INTERFACE
    Returns all answers.
    """
    items = sorted(DB["answers"], key=lambda x: x["created_at"], reverse=True)
    return [AnswerOut(**a) for a in items]

class GenerateAnswerRequest(BaseModel):
    question_id: int = Field(..., description="Question ID to answer")
    use_ai: bool = Field(True, description="If true, generate via OpenAI; otherwise require manual body")
    body: Optional[str] = Field(None, description="Manual answer body (required if use_ai is false)")

@app.post(
    "/answers",
    response_model=AnswerOut,
    tags=["Answers"],
    summary="Create/generate answer",
    description="Create an answer for a question. If use_ai is true, the server will call OpenAI to generate an answer.",
    responses={
        400: {"description": "Bad request"},
        404: {"description": "Question not found"},
        401: {"description": "Unauthorized (if manual answer creation by user)"},
    },
)
async def create_answer(
    payload: GenerateAnswerRequest,
    current_user: Optional[dict] = Depends(lambda: None)  # Optional auth; AI answers can be anonymous
):
    """
    PUBLIC_INTERFACE
    Creates an answer. When use_ai is true, generates answer content using OpenAI Chat Completions.

    Parameters:
    - payload: GenerateAnswerRequest - question_id, use_ai, body (optional)

    Returns:
    - AnswerOut
    """
    q = next((x for x in DB["questions"] if x["id"] == payload.question_id), None)
    if not q:
        raise HTTPException(status_code=404, detail="Question not found.")

    is_ai = False
    answer_body = payload.body

    if payload.use_ai:
        is_ai = True
        prompt = f"Provide a helpful, concise answer to the following question:\n\nTitle: {q['title']}\n\nDetails: {q['body']}"
        answer_body = await call_openai_chat(prompt)
    else:
        if not answer_body:
            raise HTTPException(status_code=400, detail="Manual answer requires 'body'.")
        if current_user is None:
            raise HTTPException(status_code=401, detail="Authentication required for manual answers.")

    aid = next_id("answers")
    now = datetime.utcnow()
    ans = {
        "id": aid,
        "question_id": q["id"],
        "user_id": None if is_ai else current_user["id"],
        "body": answer_body,
        "created_at": now,
        "is_ai_generated": is_ai,
    }
    DB["answers"].append(ans)
    return AnswerOut(**ans)

@app.get(
    "/questions/{question_id}/answers",
    response_model=List[AnswerOut],
    tags=["Answers"],
    summary="List answers for a question",
    description="Retrieve all answers for a specific question."
)
async def list_answers_for_question(question_id: int):
    """
    PUBLIC_INTERFACE
    Returns answers for a given question ID.
    """
    answers = [a for a in DB["answers"] if a["question_id"] == question_id]
    answers = sorted(answers, key=lambda x: x["created_at"], reverse=True)
    return [AnswerOut(**a) for a in answers]
