from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, EmailStr, Field


# Auth schemas
class Token(BaseModel):
    access_token: str = Field(..., description="JWT access token")
    token_type: str = Field(..., description="Type of token; typically 'bearer'")


class TokenData(BaseModel):
    user_id: Optional[int] = Field(None, description="User ID from token subject")


# User schemas
class UserBase(BaseModel):
    email: EmailStr = Field(..., description="User email")
    full_name: Optional[str] = Field(None, description="Full name")


class UserCreate(UserBase):
    password: str = Field(..., min_length=6, description="User password")


class UserOut(UserBase):
    id: int = Field(..., description="User identifier")

    class Config:
        from_attributes = True


# Question schemas
class QuestionBase(BaseModel):
    title: str = Field(..., min_length=3, max_length=200, description="Question title")
    body: str = Field(..., min_length=3, description="Question details")


class QuestionCreate(QuestionBase):
    pass


class QuestionOut(QuestionBase):
    id: int = Field(..., description="Question identifier")
    user_id: int = Field(..., description="Author user ID")
    created_at: datetime = Field(..., description="Creation timestamp")

    class Config:
        from_attributes = True


# Answer schemas
class AnswerBase(BaseModel):
    body: str = Field(..., min_length=1, description="Answer text")


class AnswerCreate(AnswerBase):
    question_id: int = Field(..., description="Related question ID")


class AnswerOut(AnswerBase):
    id: int = Field(..., description="Answer identifier")
    question_id: int = Field(..., description="Related question ID")
    user_id: Optional[int] = Field(None, description="Author user ID (None if AI generated)")
    created_at: datetime = Field(..., description="Creation timestamp")
    is_ai_generated: bool = Field(False, description="Flag indicating if answer was generated by AI")

    class Config:
        from_attributes = True


# Requests
class GenerateAnswerRequest(BaseModel):
    question_id: int = Field(..., description="Question ID to answer")
    use_ai: bool = Field(True, description="If true, generate via OpenAI; otherwise require manual body")
    body: Optional[str] = Field(None, description="Manual answer body (required if use_ai is false)")
